#docker build -t outlier-detection:v1 -f Dockerfile.outlier_detection_v1 .
FROM alpine
RUN  apk add python3
COPY data.csv /data.csv
COPY detect_outliers_v1.py /detect_outliers_v1.py

CMD ["python3", "/detect_outliers_v1.py"]
